name: cloud_admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_web_plugins:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.0

  # Networking & API
  http: ^1.2.0
  dio: ^5.4.0
  socket_io_client: ^3.0.0
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  flutter_dotenv: ^5.1.0

  # Navigation
  go_router: ^13.0.0

  # Firebase
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # Charts
  fl_chart: ^0.66.0

  # UI & Assets
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  
  # Data Grid / Tables (Admin specific)
  data_table_2: ^2.5.8

  # Storage & Utils
  shared_preferences: ^2.2.0
  uuid: ^4.2.2
  # Audio
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Generators
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/sounds/


